### ISSUE TITLE
Would it be better to combine Add/Remove Accounts  and Edit Metadate into General Settings?

### ISSUE THREAD

**Issue by lhorace** [jprjr/multistreamer#17]

**Comment by jprjr** [comment]
I'm not sure - so as you add/remove accounts, that changes the amount of metadata fields on the screen. Initially, I tried to avoid doing that dynamically because I wasn't really all that great at JavaScript. But now that I've got more Javascript being used (like on the chat window), I think I could pull it off.

On the other hand, I do like having the settings separated into "stuff you rarely change" and "stuff you change all the time" - I rarely touch the add/remove accounts screen, but I'm in the edit metadata screen every time I stream, so I like having a screen of just the stuff I care about in that moment.

But on yet (a third) hand, I can see it being hard to remember which setting is on which screen. Maybe I could have one page with tabs, so I could have an "Accounts" tab, "webhooks" tab, "Custom Puller" tab, etc. I think that might be the best approach

**Comment by lhorace** [comment]
A first glance, it seems like trivial to implement, perhaps with AjaxI could try looking at the code and provide a patch but I can't tell _when_ I can provide one. By then, you probably push a commit first.

**Comment by jprjr** [comment]
I got a good amount of work done on this yesterday - basically, each tab is more-or-less a part of the old form. Clicking to a different tab submits the form you're currently on, and loads up the new one. So, there's still page refreshing, but I figure it's still pretty decent, and way easier to find settings, and it was very fast for me to do - I got to keep using most of the old code instead of moving things into JavaScript

**Comment by jprjr** [comment]
And done! I just pushed out ver 9.0.0 with the new, combined settings screen.

Be sure to run `luarocks --tree=lua_modules install lua-resty-exec` to make sure you're on at least version 2.0.0. Version 9.0.0 also contains a fix for #16, it relies on a newer version of lua-resty-exec
