### ISSUE TITLE
Chatbot

### ISSUE THREAD

**Issue by luin1** [jprjr/multistreamer#22]
Is it possible to create a chat bot that would respond to simple commands ( Created by ourselves ) . Eg !www  return http://sample.website by bot.

**Comment by jprjr** [comment]
It's something I've thought about -- I think I've figured out how it could work from a user point-of-view.

I assume people don't want the account they're streaming as to act as a chatbot since that's not what they usually experience, you'd need a way to add separate chatbot accounts.

I think what might make sense is to allow users to designate "this account is a chatbot," This could disable streaming on that account, so its only able to join your stream as a chatter. You could share the chatbot account with other users the same way you share a regular account.

Then on the dashboard, there could be a list of known chatbots that you enable/disable, either created by yourself or shared by another user.

The one thing I'm not sure about is how to manage functions. You'd want some way to re-use a function you've written, I'm trying to figure out if a chatbot's functions should be saved globally (all users with access to the bot have access to the functions), or if a chatbot's functions should be scoped to the user. Maybe the server admin could put function templates into the config file, then users could use those templates or write their own from scratch?

**Comment by luin1** [comment]
That would be great,
Simple bot: https://github.com/sogehige/sogeBot - Stream stats they are great (https://raw.githubusercontent.com/sogehige/sogeBot/master/screenshots/6.png)

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
