### ISSUE TITLE
Proxy settings.

### ISSUE THREAD

**Issue by Voletek** [jprjr/multistreamer#32]
I there a way to overlap your web interface with an existing nginx configuration?....

For some reason I can't seem to get the docker IMG to get to the login screen... I've followed the video tutorial and even typed the same settings you have for the nginx proxy with no avail. Would you be able to assist? Maybe I have missed something

**Comment by jprjr** [comment]
You should only need two location directives in your nginx config, here's (roughly) what I use:

```nginx
server {
    # listen directives, server_name etc goes here

    location / {
        proxy_pass http://127.0.0.1:8081;
        proxy_request_buffering off;
        proxy_http_version 1.1;
        proxy_redirect http:// https://; # to ensure all redirects are sent with https instead of http
    }

    location /ws {
        proxy_pass http://127.0.0.1:8081;
        proxy_request_buffering off;
        proxy_http_version 1.1;
        proxy_redirect http:// https://;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

}
```

Setting the X-forwarded-proto and Host headers shouldn't actually affect anything. I have another part of my nginx config that forces all connections to https, so I have that "proxy_redirect http:// https://" directive so that all 301/302 redirects from multistreamer have https in the URL instead of http.
