### ISSUE TITLE
Questions !

### ISSUE THREAD

**Issue by TheSkream** [jprjr/multistreamer#72]
Hello,

Is the project still relevant?
Is there a way to fix the stream shutdown during an internet crash, a solution to let the ffmpeg stream open and sent a default fix image.

Thank you in advance.

**Comment by jprjr** [comment]
I think the project is still relevant, I use it every week. I haven't had time to fix a lot of bugs though, I just keep working around them (ie, I always stop the stream from OBS instead of clicking "stop push" in multistreamer). I really don't appreciate that question tbh.

For the second part, no. I have no way of hooking into the nginx rtmp module and deducing if something is a regular disconnect vs a crash, so I have no way of knowing if I should just end the stream versus go to a fallback.
