### ISSUE TITLE
Feature Request, Transitions or Static Image per Stream

### ISSUE THREAD

**Issue by a93h** [jprjr/multistreamer#82]
I use the web interface a lot, and sometimes I want to have something on one stream but not the others.
I was wondering how hard it would be to add static video or images on loop.
I am willing to donate for this feature request.
Amazing work btw.

Example. YouTube shows a diagram image while the other streams see the default setup.
or a technical difficulties image.

**Comment by jprjr** [comment]
That would be really, really difficult. I'm using ffmpeg on the command-line for relaying streams, it doesn't have a way to switch between input sources which is what you're essentially describing.

It's an idea I've been thinking about - having some small daemon that can read from multiple RTMP inputs and switch between them, use that instead of ffmpeg, it could provide a better interface for tracking what's going on, etc.

An alternative for YouTube specifically - I believe YouTube supports multiple ingests to a broadcast, and I think their web ui lets you switch between ingests. But since the other networks don't have that as a concept, and I want to try and keep everything similar between networks.

Plus I'll be honest, you may have noticed I haven't been very active on this project lately. It's an issue of how much free time I have, which lately, is not much. I appreciate you wanting to donate for the feature, but I can't buy more time in a day.

**Comment by a93h** [comment]
Thanks very much for the clarification.
I have tried to implement such a thing myself and I found it to be quite difficult.
I'll see what I can do on my end, otherwise you're correct, it's too much work.

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
