### ISSUE TITLE
User access permissions and security

### ISSUE THREAD

**Issue by triangle-stream** [jprjr/multistreamer#92]
First of all I would like to really thank you for this project. 

I'm using Multistreamer often but I was trying to make it possible to define only one user that can access the Multistreamer dashboard. 

Running via Docker, when I go to the login page, it creates a new profile for every username/password I insert into the form. In this way, even if I put a server in front of Multistreamer with some sort of auth, anyone that can be able to use the login page would also be able to use my Facebook App in order to stream to its FB page/profile (someone could use it for streaming violent/scam contents, for example, by using my App). 

Is there a way to define only one user that can have the permissions for the login? Maybe with an environment variable or something similiar? 

I read the docs but I didn't find anything BUT it is possible that there's something that I could not find: in this case I'm really sorry :)

Thank you so much!

**Comment by jprjr** [comment]
Yeah - the default Docker authentication server just auto-creates new users.

You just need to change the authentication server used, authentication is a really simple protocol - it just makes an HTTP request to some backend end-point with the username/password (as an 'Authorization' header), if it returns 200/204, authentication succeeds.

It's not mentioned in the wiki, just in the README - https://github.com/jprjr/multistreamer#setup-authentication-server

For Docker, you just set the `MULTISTREAMER_AUTH_ENDPOINT` environment variable to whatever server you want to auth against.

Alternatively, if it's just you - you can create an `htpasswd` file under the `htpasswd` folder in the Docker repo, and it will use that for authentication instead of the default.

**Comment by triangle-stream** [comment]
Thank you @jprjr ! 

Obviously I was searching in the wrong place.
